# Generated by Django 4.1.7 on 2023-03-10 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='users',
            field=models.ManyToManyField(related_name='translations', to=settings.AUTH_USER_MODEL),
        ),
    ]
