# Generated by Django 4.1.7 on 2023-03-10 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='daily_limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='today_translated_word',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='translated_words',
            field=models.IntegerField(default=0),
        ),
    ]
