# Generated by Django 4.1.7 on 2023-03-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coreuser_created_by_coreuser_daily_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreuser',
            old_name='today_translated_word',
            new_name='today_translated_words',
        ),
    ]
